node_exporter_version: "1.5.0"
node_exporter_arch: "linux-arm64"

node_exporter_dir: "node_exporter-{{ node_exporter_version }}.{{ node_exporter_arch }}"
node_exporter_url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/{{ node_exporter_dir }}.tar.gz"

