- name: Download node_exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
    dest: /tmp/node_exporter.tar.gz

- name: Extract archive
  unarchive:
    src: /tmp/node_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Copy binary to /usr/local/bin/node_exporter
  copy:
    src: "/usr/local/bin/node_exporter-1.7.0.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: '0755'
    remote_src: yes

- name: Kill old node_exporter
  shell: "pkill node_exporter || true"

- name: Start node_exporter in background
  shell: "nohup /usr/local/bin/node_exporter --web.listen-address=':9100' >/tmp/node_exporter.log 2>&1 &"

